/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.tidhar.examples

import spock.lang.Specification

class HelloWorldTest extends Specification {

    def "sayHello returns Hello, world"() {
        setup:
        HelloWorld helloWorld = new HelloWorld()
        String expectedResult = "Hello, world"

        when:
        String result = helloWorld.sayHello()

        then:
        expectedResult == result
    }

    def "sayHelloTo returns Hello, user"(){

        setup:
        HelloWorld helloWorld = new HelloWorld()
        String username = "peter.parker"
        String expectedResult = "Hello, ${username}"

        when:
        String result = helloWorld.sayHello(username)

        then:
        expectedResult == result
    }
}
