/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.tidhar.examples

class HelloWorld {

    String sayHello(){
        return "Hello, world"
    }

    String sayHello(String username){
        return "Hello, ${username}"
    }

    static void main(String[] args) {
        HelloWorld helloWorld = new HelloWorld()
        println(helloWorld.sayHello())
    }

}
